### ISSUE TITLE
Bixbase multilevel navbar looks ugly

### ISSUE THREAD

**Issue by tux-86** [Bixie/pagekit-bixbase#1]
Hello!

I currently using Bixbase theme on Pagekit. This theme works well with one level menu, but with multiple menu level (as see picture) it looks ugly.
![image](https://cloud.githubusercontent.com/assets/19769955/16784633/5e5396e0-4892-11e6-9fda-8aea7fda4323.png)

**Comment by malles** [comment]
I'm afraid that is the default UIkit styling of submenus, You are encouraged to create your own style overrides for this theme, it's called Base for a reason :)
